### ISSUE TITLE
Crd should throw error for multiple layerpresence sections

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#108]
Crd should throw error for multiple layerpresence sections

multiple-layer-presence-sections
```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "multiple-layer-presence-section"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
   query: 
     datasource:
       - name: 'prometheus'
         query: 'query'
         key: 'key'
   label:
     - name: 'label'
       value: 'value'
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: "always"
tunables:
  - name: memoryRequest
    value_type: double
    upper_bound: '300M'
    lower_bound: '150M'
    queries:
      datasource:
        - name: 'prometheus'
          query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
    sla_class:
      - response_time
      - throughput
      - resource_usage

  - name: cpuRequest
    value_type: double
    upper_bound: '3.0'
    lower_bound: '1.0'
    queries:
      datasource:
        - name: 'prometheus'
          query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
    sla_class:
      - response_time
      - throughput
      - resource_usage
```
