### ISSUE TITLE
Introduce "DYNAMIC" for the range in tunables.

### ISSUE THREAD

**Issue by kusumachalasani** [kruize/autotune#109]
In the config files like container-config , hotspot-springactuator-config.yaml we define the range of tunables.
For few tunables, the upper bound can be decided based on the "cpu" allocated to the pod (like CICompilerCount).
Also, if a customer doesn't want to send any range, autotune should be able to dynamically pick the ranges.

```
- name: CICompilerCount
  description: 'The number of compiler threads to use for compilation. By default, the number of threads is set to 2 for the server JVM, to 1 for the client JVM, and it scales to the number of cores if tiered compilation is used.'
  value_type: integer
  upper_bound: DYNAMIC
  lower_bound: 2
  sla_class:
```
