### ISSUE TITLE
AutotuneConfig: Add support for multiple metric formats for queries.

### ISSUE THREAD

**Issue by dinogun** [kruize/autotune#152]
The metrics format can be as mentioned below.  Micrometer metrics are used by both Springboot and Quarkus. mpmetrics is the microprofile standard.
```
layerPresence:
  query:
    datasource:
    - name: prometheus
      - metrics: micrometer
        query: jvm_memory_used_bytes{name="Tenured Gen"}
      - metrics: mpmetrics
        query: vendor_memoryPool_usage_bytes{name="Tenured Gen"}
      key: pod
```
Need the corresponding CRD changes as well as Java changes.
