### ISSUE TITLE
AutotuneConfig: Add support for feature presence

### ISSUE THREAD

**Issue by dinogun** [kruize/autotune#154]
Every autotune `layer` usually supports several features. However not all of them will be present or being used for every deployment. Need a way to check for the presence of a feature similar to layer presence.

```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "quarkus"
layer_name: quarkus
layer_level: 2
details: quarkus tunables
layer_presence:
  label:
  - name: app.kubernetes.io/layer
    value: quarkus
feature_presence:
- name: core
  presence: always
- name: agroal
  query:
    datasource:
    - name: prometheus
      - metrics: micrometer
        query: agroal
      - metrics: mpmetrics
        query: vendor_agroal
      key: pod
- endpoint: /q/info
    key: features
# hibernate-orm is currently detected through a label
- name: hibernate-orm
  label:
  - name: app.kubernetes.io/quarkus_feature
    value: hibernate-orm
tunables:
- name: quarkus.thread-pool.core-threads
  description: 'The core thread pool size. This number of threads will always be kept alive.'
  value_type: integer
  upper_bound: "10"
  lower_bound: "1"
  features:
  - core
  sla_class:
  - response_time
  - throughput
- name: quarkus.thread-pool.queue-size
  description: 'The queue size'
  value_type: integer
  upper_bound: "100"
  lower_bound: "1"
  features:
  - core
  sla_class:
  - response_time
  - throughput
  - resource_usage
- name: quarkus.hibernate-orm.jdbc.statement-fetch-size
  description: 'How many rows are fetched at a time by the JDBC driver.'
  value_type: integer
  upper_bound: "50"
  lower_bound: "1"
  features:
  - hibernate-orm
  sla_class:
  - response_time
  - throughput
```
