### ISSUE TITLE
Validation check for direction with respect to sla_class

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#158]
Validate direction with respect to sla_class
ex: For sla_class: response_time direction is always minimize whereas setting direction to maximize doesn't make sense
Expected behavior: direction: maximize for sla_class: response_time should throw an error

invalid-direction-for-slaclass yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "invalid-direction-for-slaclass"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "maximize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
