### ISSUE TITLE
Adding new autotuneconfig object for container layer doesn't update the same layer info

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#171]
Adding new autotuneconfig object for the container layer doesn't update the same layer info instead it is displayed separately

Steps to reproduce
- Deploy autotune using ./deploy.sh
- Copy container config  
- Change the name of object and add a new tunable say memoryLimit
- Apply new autotune config 

yaml
```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "tunable-memorylimit"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: always
tunables:
  - name: memoryRequest
    value_type: double
    upper_bound: '250M'
    lower_bound: '100M'
    queries:
      datasource:
        - name: 'prometheus'
          query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
    sla_class:
      - response_time
      - throughput
      - resource_usage
  
  - name: memoryLimit
    value_type: double
    upper_bound: '350M'
    lower_bound: '150M'
    queries:
      datasource:
        - name: 'prometheus'
          query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
    sla_class:
      - response_time
      - throughput
      - resource_usage
      
  - name: cpuRequest
    value_type: double
    upper_bound: '3.0'
    lower_bound: '1.0'
    queries:
      datasource:
        - name: 'prometheus'
          query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
    sla_class:
      - response_time
      - throughput
      - resource_usage

```

Actual result
```
[
    {
        "layer_level": 0,
        "tunables": [
            {
                "value_type": "double",
                "lower_bound": "150M",
                "name": "memoryRequest",
                "upper_bound": "300M"
            },
            {
                "value_type": "double",
                "lower_bound": "1.0",
                "name": "cpuRequest",
                "upper_bound": "3.0"
            }
        ],
        "layer_name": "container",
        "layer_details": "generic container tunables"
    },
    {
        "layer_level": 0,
        "tunables": [
            {
                "value_type": "double",
                "lower_bound": "100M",
                "name": "memoryRequest",
                "upper_bound": "250M"
            },
            {
                "value_type": "double",
                "lower_bound": "150M",
                "name": "memoryLimit",
                "upper_bound": "350M"
            },
            {
                "value_type": "double",
                "lower_bound": "1.0",
                "name": "cpuRequest",
                "upper_bound": "3.0"
            }
        ],
        "layer_name": "container",
        "layer_details": "generic container tunables"
    }
        ],
        "layer_name": "quarkus",
        "layer_details": "quarkus tunables"
    }
]
```
Expeted result
```
[{
    "layer_level": 0,
    "tunables": [
        {
            "value_type": "double",
            "lower_bound": "100M",
            "name": "memoryRequest",
            "upper_bound": "250M"
        },
        {
            "value_type": "double",
            "lower_bound": "150M",
            "name": "memoryLimit",
            "upper_bound": "350M"
        },
        {
            "value_type": "double",
            "lower_bound": "1.0",
            "name": "cpuRequest",
            "upper_bound": "3.0"
        }
    ]
}]
```
