### ISSUE TITLE
DA is accepting duplicate tunables and is it also displayed in  API results

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#196]
DA should not accept duplicate tunables instead should throw an error 

**Steps to recreate:**

- Deploy autotune
- copy container autotune config
- Modify the config yaml by duplicating any tunable details by keeping metadata same as previous

**Example yaml:**
```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "container"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: always
tunables:
  - name: memoryRequest
    value_type: double
    upper_bound: '300M'
    lower_bound: '150M'
    queries:
      datasource:
        - name: 'prometheus'
          query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
    sla_class:
      - response_time
      - throughput
      - resource_usage

  - name: memoryRequest
    value_type: double
    upper_bound: '300M'
    lower_bound: '150M'
    queries:
      datasource:
        - name: 'prometheus'
          query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
    sla_class:
      - response_time
      - throughput
      - resource_usage

  - name: cpuRequest
    value_type: double
    upper_bound: '3.0'
    lower_bound: '1.0'
    queries:
      datasource:
        - name: 'prometheus'
          query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
    sla_class:
      - response_time
      - throughput
      - resource_usage
```

**Actual result:**

```
[{
    "layer_level": 0,
    "tunables": [
        {
            "value_type": "double",
            "lower_bound": "150M",
            "name": "memoryRequest",
            "upper_bound": "300M"
        },
        {
            "value_type": "double",
            "lower_bound": "150M",
            "name": "memoryRequest",
            "upper_bound": "300M"
        },
        {
            "value_type": "double",
            "lower_bound": "1.0",
            "name": "cpuRequest",
            "upper_bound": "3.0"
        }
    ],
    "layer_name": "container",
    "layer_details": "generic container tunables"
}]
```
