### ISSUE TITLE
Fix error in operator-deployment yaml

### ISSUE THREAD

**Issue by ShishirH** [kruize/autotune#23]
The yaml https://github.com/kruize/autotune/blob/master/manifests/autotune-operator-deployment.yaml
currently uses the key `autotune-config-key` for the envs, which will give an error. It should be replaced by the name of the configmap, `autotune-config`

```
apiVersion: v1
data:
  autotune-config-key: |+
    CLUSTER_TYPE:"kubernetes"
    K8S_TYPE:"minikube"
    AUTH_TYPE:"OIDC"
    AUTH_TOKEN:""
    MONITORING_AGENT:"prometheus"
    MONITORING_SERVICE:""
    MONITORING_AGENT_ENDPOINT:""
    LOGGING_LEVEL:"INFO"

kind: ConfigMap
metadata:
  name: autotune-config
  namespace: monitoring
```

```
        env:
          - name: CLUSTER_TYPE
            valueFrom:
              configMapKeyRef:
                name: autotune-config-key <-- replace this with name of the configmap
                key: CLUSTER_TYPE 
```
