### ISSUE TITLE
Datasource name in application autotune yaml can not be blank or invalid

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#252]
Datasource name in application autotune yaml can not be blank or invalid

**blank-datasource-name**
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "blank-datasource-name"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
  datasource:
    name: " "
    value: "prometheus_URL"
```

**invalid-datasource-name**
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "invalid-datasource-name"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
  datasource:
    name: "xyz"
    value: "prometheus_URL"
```
