### ISSUE TITLE
DA is throwing repeated error messages for layer config yaml with step value zero

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#255]
DA is throwing repeated error messages for layer config yaml with step value zero

**Actual error message**
```
com.autotune.dependencyAnalyzer.exceptions.InvalidValueException: Tunable step cannot be 0Tunable step cannot be 0Tunable step cannot be 0
```
**Expected error message**
```
com.autotune.dependencyAnalyzer.exceptions.InvalidValueException: Tunable step cannot be 0
```
**layer config yaml**

```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "zero-step"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: always
tunables:
- name: memoryRequest
  value_type: double
  upper_bound: 300
  lower_bound: 150
  step: 0
  queries:
    datasource:
    - name: 'prometheus'
      query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
  sla_class:
  - response_time
  - throughput
  - resource_usage

- name: cpuRequest
  value_type: double
  upper_bound: 3.0
  lower_bound: 1.0
  step: 0.01
  queries:
    datasource:
    - name: 'prometheus'
      query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
  sla_class:
  - response_time
  - throughput
  - resource_usage
```
