### ISSUE TITLE
Applying application autotune yaml with datasource other than prometheus throws error

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#264]
Applying application autotune yaml with datasource other than prometheus throws following error

`Error : com.autotune.analyzer.exceptions.InvalidValueException: function_variable: transaction_response_time datasource not supported`

**Example yaml**
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "valid-datasource-url"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus-test"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
  datasource:
    name: "prometheus-test"
    value: "PROMETHEUS_URL"
```

**Steps to reproduce:**

- Deploy autotune
- Expose prometheus : `kubectl expose service prometheus-k8s --type=NodePort --target-port=9090 --name=prometheus-test -n monitoring`
- Get the url: `minikube service list | grep "prometheus-test" | awk '{print $8}'`
- Use the above datasource and url in application autotune yaml
- Apply the application autotune yaml
