### ISSUE TITLE
Application autotune YAML with null/no hpo_algo_impl value needs validation from DA

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#265]
Application autotune YAML with null/no hpo_algo_impl value needs validation from DA

**null-hpo-algo-impl yaml**
```
apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "null-hpo-algo-impl"
  namespace: "default"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    hpo_algo_impl: NULL
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
```

**no-hpo-algo-impl-value**
```
apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "no-hpo-algo-impl-value"
  namespace: "default"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    hpo_algo_impl: 
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
```
