### ISSUE TITLE
Autotune should throw an error for Layer config with null/no step value

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#269]
Autotune should throw an error for Layer config with null/no step value
 
**null-step yaml**
```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "null-step"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: always
tunables:
- name: memoryRequest
  value_type: double
  upper_bound: 300
  lower_bound: 150
  step: NULL
  queries:
    datasource:
    - name: 'prometheus'
      query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
  sla_class:
  - response_time
  - throughput
  - resource_usage

- name: cpuRequest
  value_type: double
  upper_bound: 3.0
  lower_bound: 1.0
  step: NULL
  queries:
    datasource:
    - name: 'prometheus'
      query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
  sla_class:
  - response_time
  - throughput
  - resource_usage

```

**no-step-value yaml**
```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "no-step-value"
layer_name: container
layer_level: 0
details: generic container tunables
layerPresence:
  # This layer is assumed to be available by default for all applications.
  presence: always
tunables:
- name: memoryRequest
  value_type: double
  upper_bound: 300
  lower_bound: 150
  step: 
  queries:
    datasource:
    - name: 'prometheus'
      query: 'container_memory_working_set_bytes{$CONTAINER_LABEL$="", $POD_LABEL$="$POD$"}'
  sla_class:
  - response_time
  - throughput
  - resource_usage

- name: cpuRequest
  value_type: double
  upper_bound: 3.0
  lower_bound: 1.0
  step:
  queries:
    datasource:
    - name: 'prometheus'
      query: '(container_cpu_usage_seconds_total{$CONTAINER_LABEL$!="POD", $POD_LABEL$="$POD$"}[1m])'
  sla_class:
  - response_time
  - throughput
  - resource_usage
```
