### ISSUE TITLE
Applying a valid layer config after applying a layer config with blank-layer-presence-label-name fails by throwing NullPointerException

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#271]
Applying a valid layer config after applying a layer config with blank-layer-presence-label-name fails by throwing NullPointerException.

Applying layer config with blank-layer-presence-label-name throws NullPointerException https://github.com/kruize/autotune/issues/149. Now if we apply a valid layer config it creates the object but along with NullPointerException.

**Steps to recreate:**

- Deploy autotune
- Copy quarkus layer config. Modify it by replacing the layer_presence label name with a blank.
- Apply the layer config YAML
- Now replace blank with a valid label name and re-apply
 
**blank-layer-presence-label-name yaml**

```
apiVersion: "recommender.com/v1"
kind: "AutotuneConfig"
metadata:
  name: "blank-layer-presence-label-name"
layer_name: quarkus
layer_level: 2
details: quarkus tunables
layerPresence:
  label:
  - name: ' '
    value: quarkus
tunables:
- name: quarkus.thread-pool.core-threads
  description: 'The core thread pool size. This number of threads will always be kept alive.'
  value_type: integer
  upper_bound: "10"
  lower_bound: "1"
  sla_class:
  - response_time
  - throughput
- name: quarkus.thread-pool.queue-size
  description: 'The queue size'
  value_type: integer
  upper_bound: "100"
  lower_bound: "1"
  sla_class:
  - response_time
  - throughput
  - resource_usage
- name: quarkus.hibernate-orm.jdbc.statement-fetch-size
  description: 'How many rows are fetched at a time by the JDBC driver.'
  value_type: integer
  upper_bound: "50"
  lower_bound: "1"
  sla_class:
  - response_time
  - throughput
  - resource_usage
```
 
[autotune.log](https://github.com/kruize/autotune/files/6722178/autotune.log)
