### ISSUE TITLE
Expected some validation for required fileds  against operator-crd 

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#46]
Applying an app autotune yaml without the required fields works fine. Used the example/app-autotune.yaml and removed the objective function which is marked as required. Applied this yaml.

```
apiVersion: "recommender.com/v1beta1"
kind: "Autotune"
metadata:
 name: "no-objective-function"
 namespace: "default"
sla:
 sla_class: "response_time"
 direction: "minimize"
 function_variables:
 - name: "transaction_response_time"
   query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
   datasource: "prometheus"
   value_type: "double" 
 mode: "show"
 selector: 
   matchLabel: "app.kubernetes.io/name"
   matchLabelValue: "petclinic-deployment"
   matchRoute: ""
   matchURI: ""
   matchService: ""
 ```
**Steps to recreate**
- Copy examples/app-autotune.yaml
- Delete the objective function field
- kubectl apply -f autotune-operator-crd.yaml
- kubectl apply -f app-autotune.yaml
