### ISSUE TITLE
DA is not throwing error message for blank and invalid objective function

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#82]
Expected validation from dependency analyzer for blank and invalid objective function

Blank objective function yaml

```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "blank-objective-function"
spec:
  sla:
    objective_function: " "
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```

invalid objective function autotune yaml

```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "invalid-objective-function"
spec:
  sla:
    objective_function: "tranme"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
[blank-objective-function-autotune.log](https://github.com/kruize/autotune/files/5851365/blank-objective-function-autotune.log)
[invalid-objective-function-autotune.log](https://github.com/kruize/autotune/files/5851376/invalid-objective-function-autotune.log)
