### ISSUE TITLE
Expected error for multiple direction sections

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#87]
Expected error messages for multiple direction sections

yaml for multiple-direction-sections

```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-direction-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    direction: "maximize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
