### ISSUE TITLE
Required validation for multiple objective_function sections

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#88]
Expected error messages for multiple objective_function sections

yaml for multiple-objective-function-sections

```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-objective-function-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    objective_function: "transaction_throughput"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
