### ISSUE TITLE
Required validation for blank, invalid, multiple-function-variable-query-sections 

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#90]
validation is required for blank , invalid and multiple-function-variable-query-sections

blank-function-variable-query yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "blank-function-variable-query"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: " "
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```

invalid-function-variable-query yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "invalid-function-variable-query"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "applimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
 
multiple-function-variable-query-sections yaml
``` 
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-function-variable-query-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
