### ISSUE TITLE
multiple function_variable value_type sections needs validation

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#91]
validation is required multiple-function-variable-value-type-sections

multiple-function-variable-value-type-sections yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-function-variable-value-type-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
      value_type: "float"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
