### ISSUE TITLE
Require validation for multiple-mode-sections

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#92]
validation is required multiple-mode-sections

multiple-mode-sections yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-mode-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  mode: "try"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
