### ISSUE TITLE
MatchlabelValue needs validation for blank and multiple-labelvalue sections 

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#94]
Require validation for blank and multiple-labelvalue-sections

blank-labelvalue yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "blank-labelvalue"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: " "
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
multiple-labelvalue-sections yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-labelvalue-sections"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchLabelValue: "petclinic-deployment-0"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
