### ISSUE TITLE
validate multiple sla_class

### ISSUE THREAD

**Issue by shruacha1234** [kruize/autotune#95]
Require validation for blank and multiple-slaclass

multiple-slaclass yaml
```
apiVersion: "recommender.com/v1"
kind: "Autotune"
metadata:
 name: "multiple-slaclass"
spec:
  sla:
    objective_function: "transaction_response_time"
    sla_class: "response_time"
    sla_class: "throughput"
    direction: "minimize"
    function_variables:
    - name: "transaction_response_time"
      query: "application_org_acme_microprofile_metrics_PrimeNumberChecker_checksTimer_mean_seconds"
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "petclinic-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: "https"
```
